FROM nginx:1.14-alpine

LABEL Maintainer="maoguangqing@yit.com"

# 删除nginx默认配置文件
RUN rm -rf /etc/nginx/conf.d/default.conf

# 拷贝nginx配置文件
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY config/yit_h5.conf /etc/nginx/conf.d/yit_h5.conf

# 拷贝网站静态资源文件
COPY dist /yit/www/h5
RUN chown -R nginx:nginx /yit/www